language: go
go:
  - 1.6
before_install:
  - go get -v -d golang.org/x/sys/unix golang.org/x/tools/cmd/cover github.com/golang/lint/golint
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
script:
  - make -j4 check GOTEST_FLAGS=-v
